In [1]:
import tensorflow as tf

In [2]:
physical_devices = tf.config.list_physical_devices('GPU')
physical_devices

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
tf.config.experimental.set_memory_growth(physical_devices[0], True)

#### Initializing methods

In [4]:
x = tf.constant(4)
x

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [5]:
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [6]:
x = tf.constant([[1,2,3],[4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [7]:
x = tf.ones((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [8]:
x = tf.zeros((2,3))
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [9]:
x = tf.eye(3) # Identity matrix
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [10]:
x = tf.random.normal((2,3)) # mean=0, std=1
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.53243804, -0.21968164, -0.4388611 ],
       [-1.0692341 ,  2.0441566 , -0.14958681]], dtype=float32)>

In [11]:
x = tf.random.uniform((3,2), minval=0, maxval=1)
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7796612 , 0.847813  ],
       [0.18396091, 0.6234549 ],
       [0.15225291, 0.94834876]], dtype=float32)>

In [12]:
x = tf.range(10)
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

#### Converting (casting) to different type

In [13]:
x = tf.cast(x, dtype=tf.float32) # Converting dtype
x

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

#### Mathematical Operations

In [14]:
x = tf.constant([3,4,6])
y = tf.constant([4,3,2])
z = tf.add(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 7, 8])>

In [15]:
z = x + y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 7, 8])>

In [16]:
z = tf.subtract(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-1,  1,  4])>

In [17]:
z = x - y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-1,  1,  4])>

In [18]:
z = tf.divide(x,y)
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.75      , 1.33333333, 3.        ])>

In [19]:
z = x/y
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.75      , 1.33333333, 3.        ])>

In [20]:
z = tf.multiply(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([12, 12, 12])>

In [21]:
z = x * y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([12, 12, 12])>

In [22]:
z = tf.tensordot(x,y, axes=1)
z

<tf.Tensor: shape=(), dtype=int32, numpy=36>

In [23]:
z = tf.reduce_sum(x*y, axis=0)
z

<tf.Tensor: shape=(), dtype=int32, numpy=36>

In [24]:
z = x**2
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 36])>

In [25]:
x = tf.random.normal((3,2))
y = tf.random.normal((2,3))
z = tf.matmul(x,y)
z

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.12038616,  0.48211908,  0.2233798 ],
       [-0.25260112,  1.2330425 ,  0.26679873],
       [ 0.37050796, -1.5264894 , -0.64856184]], dtype=float32)>

In [26]:
z = x@y
z

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.12038616,  0.48211908,  0.2233798 ],
       [-0.25260112,  1.2330425 ,  0.26679873],
       [ 0.37050796, -1.5264894 , -0.64856184]], dtype=float32)>

#### Indexing

In [27]:
x = tf.constant([2,3,4,5,6,7,8,9])
x[:]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7, 8, 9])>

In [28]:
x[1:]

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([3, 4, 5, 6, 7, 8, 9])>

In [29]:
x[3:4]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([5])>

In [30]:
x[::2] # Skipping

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8])>

In [31]:
x[::-1] # Reverse

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([9, 8, 7, 6, 5, 4, 3, 2])>

In [32]:
indices = tf.constant([2,3,5,7]) # Selecting the values with multiple index
x_ind = tf.gather(x, indices)
x_ind

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 5, 7, 9])>

Can be done for multi-dimensional as well. Same as python, numpy.

#### Reshaping

In [33]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [34]:
x = tf.reshape(x, (3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [35]:
x = tf.transpose(x) # perm=[1,0]
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])>